config/routes.rb
App::Application.routes.draw do



  #match 'admin/order/:id/purchase/new', :to => 'admin/_purchases#new'

  match 'admin/shipments/print', :to => "admin/shipments#print"

  match 'admin/shipments/print_preview', :to => "admin/shipments#print_preview"


  match 'admin/shipments/download', :to => "admin/shipments#download"

  match 'admin/purchases/download', :to => "admin/purchases#download"

  match '/admin/shipments', :to => "admin/shipments#home"

  match '/admin/orders/:order_id/shipments/new', :to => "admin/shipments#add"

  match 'tracking/:id',  :to => "orders#track"

  match '/checkout' => 'checkout#edit', :state => 'delivery', :as => :checkout

  resources :comments
  #resources :tickets



  namespace :admin do
    resources :suppliers
    resources :comments
    resources :tickets
    resources :excels
    resources :refunds
    resources :black_lists

    resources :purchases do
      resources :receive_products
      resources :return_products
    end
  end




end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
  require 'spree/gateway_error'
  before_filter :initialize_txn_partials
  before_filter :initialize_order_events
  before_filter :load_order, :only => [:fire, :resend, :history, :user]

  respond_to :html

  def index

    params[:search] ||= {}
    params[:search][:completed_at_is_not_null] ||= '1' if Spree::Config[:show_only_complete_orders_by_default]
    @show_only_completed = params[:search][:completed_at_is_not_null].present?
    params[:search][:meta_sort] ||= @show_only_completed ? 'completed_at.desc' : 'created_at.desc'
    #params[:search][:state] ||= "cart"

    @search = Order.metasearch(params[:search])

    if !params[:search][:created_at_greater_than].blank?
      params[:search][:created_at_greater_than] = Time.zone.parse(params[:search][:created_at_greater_than]).beginning_of_day rescue ""
    end

    if !params[:search][:created_at_less_than].blank?
      params[:search][:created_at_less_than] = Time.zone.parse(params[:search][:created_at_less_than]).end_of_day rescue ""
    end

    if @show_only_completed
      params[:search][:completed_at_greater_than] = params[:search].delete(:created_at_greater_than)
      params[:search][:completed_at_less_than] = params[:search].delete(:created_at_less_than)
    end

    @orders = Order.where("state != 'cart'").metasearch(params[:search]).paginate(
        :include => [:user, :shipments, :payments],
        :per_page => Spree::Config[:orders_per_page],
        :page => params[:page])

    respond_with(@orders)
  end

  def home
    params[:search] ||= {}
    params[:search][:completed_at_is_not_null] ||= '1' if Spree::Config[:show_only_complete_orders_by_default]
    @show_only_completed = params[:search][:completed_at_is_not_null].present?
    params[:search][:meta_sort] ||= @show_only_completed ? 'completed_at.desc' : 'created_at.desc'
    #params[:search][:state] ||= "cart"

    @search = Order.metasearch(params[:search])

    if !params[:search][:created_at_greater_than].blank?
      params[:search][:created_at_greater_than] = Time.zone.parse(params[:search][:created_at_greater_than]).beginning_of_day rescue ""
    end

    if !params[:search][:created_at_less_than].blank?
      params[:search][:created_at_less_than] = Time.zone.parse(params[:search][:created_at_less_than]).end_of_day rescue ""
    end

    if @show_only_completed
      params[:search][:completed_at_greater_than] = params[:search].delete(:created_at_greater_than)
      params[:search][:completed_at_less_than] = params[:search].delete(:created_at_less_than)
    end

    @orders = Order.where("state != 'cart'").metasearch(params[:search]).paginate(
        :include => [:user, :shipments, :payments],
        :per_page => Spree::Config[:orders_per_page],
        :page => params[:page])

    respond_with(@orders)
  end

  def show
    load_order
    respond_with(@order)
  end




  def new
    @order = Order.create
    respond_with(@order)
  end

  def edit
    load_order
    respond_with(@order)
  end



  def update
    return_path = nil
    load_order
    if @order.update_attributes(params[:order]) && @order.line_items.present?
      unless @order.complete?

        if params[:order].key?(:email)
          shipping_method = @order.available_shipping_methods(:front_end).first
          if shipping_method
            @order.shipping_method = shipping_method
            @order.create_shipment!
            return_path = edit_admin_order_shipment_path(@order, @order.shipment)
          else
            flash[:error] = t('errors.messages.no_shipping_methods_available')
            return_path = user_admin_order_path(@order)
          end
        else
          return_path = user_admin_order_path(@order)
        end

      else
        return_path = admin_order_path(@order)
      end
    else
      @order.errors.add(:line_items, t('errors.messages.blank'))
    end

    respond_with(@order) do |format|
      format.html do
        if return_path
          redirect_to return_path
        else
          render :action => :edit
        end
      end
    end
  end


  def fire
    # TODO - possible security check here but right now any admin can before any transition (and the state machine
    # itself will make sure transitions are not applied in the wrong state)
    event = params[:e]
    if @order.send("#{event}")
      flash.notice = t('order_updated')
    else
      flash[:error] = t('cannot_perform_operation')
    end
  rescue Spree::GatewayError => ge
    flash[:error] = "#{ge.message}"
  ensure
    respond_with(@order) { |format| format.html { redirect_to :back } }
  end

  def resend
    OrderMailer.confirm_email(@order, true).deliver
    flash.notice = t('order_email_resent')

    respond_with(@order) { |format| format.html { redirect_to :back } }
  end

  def user
    @order.build_bill_address(:country_id => Spree::Config[:default_country_id]) if @order.bill_address.nil?
    @order.build_ship_address(:country_id => Spree::Config[:default_country_id]) if @order.ship_address.nil?
  end

  private

  def load_order
    @order ||= Order.find_by_number(params[:id], :include => :adjustments) if params[:id]
    @order
  end

  # Allows extensions to add new forms of payment to provide their own display of transactions
  def initialize_txn_partials
    @txn_partials = []
  end

  # Used for extensions which need to provide their own custom event links on the order details view.
  def initialize_order_events
    @order_events = %w{cancel resume}
  end

end

app/controllers/orders_controller.rb
class OrdersController < Spree::BaseController
  respond_to :html

  helper :products


  def show
    @order = Order.find_by_number(params[:id])

  end

  def update
    @order = current_order
    if @order.update_attributes(params[:order])
      @order.line_items = @order.line_items.select {|li| li.quantity > 0 }
      respond_with(@order) { |format| format.html { redirect_to cart_path } }
    else
      respond_with(@order) 
    end
  end

  # Shows the current incomplete order from the session
  def edit
    @order = current_order(true)
  end

  def track

  end



  # Adds a new item to the order (creating a new order if none already exists)
  #
  # Parameters can be passed using the following possible parameter configurations:
  #
  # * Single variant/quantity pairing
  # +:variants => {variant_id => quantity}+
  #
  # * Multiple products at once
  # +:products => {product_id => variant_id, product_id => variant_id}, :quantity => quantity +
  # +:products => {product_id => variant_id, product_id => variant_id}}, :quantity => {variant_id => quantity, variant_id => quantity}+
  def populate
    @order = current_order(true)

    params[:products].each do |product_id,variant_id|
      quantity = params[:quantity].to_i if !params[:quantity].is_a?(Hash)
      quantity = params[:quantity][variant_id].to_i if params[:quantity].is_a?(Hash)
      @order.add_variant(Variant.find(variant_id), quantity) if quantity > 0
    end if params[:products]

    params[:variants].each do |variant_id, quantity|
      quantity = quantity.to_i
      @order.add_variant(Variant.find(variant_id), quantity) if quantity > 0
    end if params[:variants]

    respond_with(@order) { |format| format.html { redirect_to cart_path } }
  end

  def empty
    if @order = current_order
      @order.line_items.destroy_all
    end
    
    respond_with(@order) { |format| format.html { redirect_to cart_path } }
  end

  def accurate_title
    @order && @order.completed? ? "#{Order.human_name} #{@order.number}" : I18n.t(:shopping_cart)
  end
end

app/views/admin/orders/_form.html.erb
<% if @line_item.try(:errors).present? %>
  <%= render 'shared/error_messages', :target => @line_item %>
<% end %>

<%= form_for(@order, :url => admin_order_url(@order), :html => { :method => :put}) do |f| %>
  <%= f.hidden_field :number %>
  <table class="index">
    <tbody id='line-items'>
      <tr>
        <%= hook :admin_order_form_line_items_headers do %>
          <th><%= t('item_description') %></th>
          <th class="price"><%= t('price') %></th>
          <th class="qty"><%= t('qty') %></th>
          <th class="total"><span><%= t('total') %></span></th>
        <% end %>
        <th class="orders-actions"><%= hook :admin_order_form_line_items_header_actions %></th>
      </tr>
      <%= f.fields_for :line_items do |li_form| %>
        <%= render :partial => "admin/orders/line_item", :locals => { :f => li_form } %>
      <% end %>
    </tbody>
    <%= hook :admin_order_form_subtotal do %>
      <tbody id='subtotal'>
        <tr id="subtotal-row">
          <td colspan="3"><b><%= t('subtotal') %>:</b></td>
          <td class="total"><span><%= number_to_currency @order.item_total %></span></td>
          <td></td>
        </tr>
      </tbody>
    <% end %>
    <%= hook :admin_order_form_adjustments do %>
      <tbody id="order-charges">
        <% @order.adjustments.each do |adjustment| %>
          <tr>
            <td colspan="3"><strong><%= adjustment.label %></strong></td>
            <td class="total"><span><%= number_to_currency adjustment.amount %></span></td>
            <td></td>
          </tr>
        <% end %>
      </tbody>
    <% end %>
    <%= hook :admin_order_form_total do %>
      <tbody id='order-total'>
        <tr>
          <td colspan="3"><b><%= t('order_total') %>:</b></td>
          <td class="total"><span id="order_total"><%= number_to_currency @order.total %></span></td>
          <td></td>
        </tr>
      </tbody>
    <% end %>
  </table>

  <%= hook :admin_order_form_buttons do %>
    <p class="form-buttons">
      <%= button @order.complete? ? t('update') : t('continue') %>
      <%= t("or") %> <%= link_to t("actions.cancel"), admin_orders_url %>
    </p>
  <% end %>

<% end %>

<script type="text/javascript">
  <%= render 'admin/shared/update_order_state.js' %>
</script>

<%= javascript_include_tag 'admin/orders/edit_form.js' %>

app/views/admin/orders/edit.html.erb
<%= csrf_meta_tag %>
<div class='order-links'>
  <%= hook :admin_order_edit_buttons do %>
    <div class='toolbar'>
      <%= event_links %>
    </div>
    <div class='toolbar'>
      <%= button_link_to(t("resend"), resend_admin_order_url(@order), :method => :post, :icon => 'send-email') if @order.user %>
    </div>
  <% end %>
</div>

<%= render :partial => 'admin/shared/order_tabs', :locals => {:current => "Order Details"} %>

<%= hook :admin_order_edit_header do %>
  <%= render "shared/error_messages", :target => @order %>
<% end %>

<%#= render :partial => "add_product" %>

<%= hook :admin_order_edit_form do %>
  <div id="order-form-wrapper">
    <%= render :partial => 'form', :locals => {:order => @order} %>
  </div>
<% end %>

<% content_for :head do %>
  <%= javascript_tag "var expand_variants = true;" %>
  <%= javascript_include_tag 'admin/orders/edit.js' %>
  <%= stylesheet_link_tag 'admin/edit_orders.css' %>
<% end %>

app/views/admin/orders/home.html.erb
<div class='toolbar order-links'>

      <%= button_link_to "Shipment File", "/admin/shipments/download", :icon => 'pages'  %>

  <%= hook :admin_order_show_buttons do %>
      <%= button_link_to(t('shipment_report'), "/admin/shipments/print.pdf", :method => :get, :target => "_blank", :icon => 'pdf') %>
  <% end %>
</div>

<%= render :partial => 'admin/shared/order_sub_menu' %>

<h1><%= t("listing_shipments") %></h1>


<table class="index" id='listing_orders'>
  <thead>
  <tr>
    <%= hook :admin_orders_index_headers do %>
        <% if @show_only_completed %>
            <th><%= sort_link @search, :completed_at, t("activerecord.attributes.order.completed_at") %></th>
        <% else %>
            <th><%= sort_link @search, :created_at, t("order_date") %></th>
        <% end %>
        <th><%= sort_link @search, :number, t("order_number") %></th>


        <th><%= t("purchase_total") %></th>
        <th><%= sort_link @search, :shipment_state, t("shipment_state") %></th>
        <th><%= sort_link @search, :email, t("customer") %></th>

    <% end %>
    <th>
      <%= hook :admin_orders_index_header_actions %>
    </th>
  </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
      <tr style="background: #E3E3E3;">
        <%- locals = {:order => order} %>
        <%= hook :admin_orders_index_rows, locals do %>
            <td style="vertical-align: middle;"><%= (@show_only_completed ? order.completed_at : order.created_at).to_date %></td>
            <td style="vertical-align: middle;">
              <%= link_to order.number, admin_order_path(order) %>
            </td>
            <td style="vertical-align: middle;"><%= "#{order.inventory_units.in_stock.size} in #{order.inventory_units.size}" %></td>
            <td style="vertical-align: middle;"><%= link_to t("shipment_states.#{order.shipment_state}"), admin_order_shipments_path(order) if order.shipment_state %></td>
            <td style="vertical-align: middle;"><%= order.email %></td>

        <% end %>
        <td class='actions' style="vertical-align: middle;">
          <%= hook :admin_orders_index_row_actions, locals do %>

              <%= link_to_edit_url admin_order_shipments_url(order), :title => "admin_edit_#{dom_id(order)}" %>
          <% end %>
        </td>
      </tr>
      <tr>
        <td colspan="6">

          <table class="index2" id='listing_orders'>

            <% order.inventory_units.each do |inventory_unit| %>
                <tr>
                  <td>
                    <%#= image_tag "admin/icons/playback_play.png" %>

                  </td>
                  <td valign="top" width="120px;" style="text-align:right;"> -</td>
                  <td style="min-width: 300px;">

                    <%= inventory_unit.variant.product.name %>
                    <%#= "(" + variant_options(inventory_unit.variant) + ")" unless inventory_unit.variant.option_values.empty? %>

                    <% item = LineItem.find_all_by_order_id_and_variant_id(inventory_unit.order_id, inventory_unit.variant_id).last %>

                    <%name = "" %>
                    <% item.product_customizations.each do |customization| %>
                        <% next if customization.customized_product_options.all? { |cpo| cpo.value.empty? } %>

                        <% if customization.product_customization_type.name.downcase == 'name' %>

                            <% customization.customized_product_options.each do |option| %>
                                <% next if option.value.empty? %>

                                <% partial = option.customizable_product_option.name %>
                                <% lookup=ActionView::LookupContext.new(ActionController::Base.view_paths, {:formats => [:html]}) %>
                                <% if lookup.exists?("orders/custom_fields/#{partial}", nil, true) %>
                                    <%= render :partial => "orders/custom_fields/#{partial}", :locals=>{:option => option} %>
                                <% else %>
                                    <% name = option.value %>
                                <% end %>
                            <% end %>
                        <% end %>
                    <% end %>
                    <%= "+ #{name}" %>


                    <% number = "" %>
                    <% item.product_customizations.each do |customization| %>
                        <% next if customization.customized_product_options.all? { |cpo| cpo.value.empty? } %>

                        <% if customization.product_customization_type.name.downcase == 'number' %>

                            <% customization.customized_product_options.each do |option| %>
                                <% next if option.value.empty? %>

                                <% partial = option.customizable_product_option.name %>
                                <% lookup=ActionView::LookupContext.new(ActionController::Base.view_paths, {:formats => [:html]}) %>
                                <% if lookup.exists?("orders/custom_fields/#{partial}", nil, true) %>
                                    <%= render :partial => "orders/custom_fields/#{partial}", :locals=>{:option => option} %>
                                <% else %>
                                    <% number = option.value %>
                                <% end %>
                            <% end %>
                        <% end %>
                    <% end %>
                     <%= "+ No.#{number}" %>

                    <% item.ad_hoc_option_values.each do |pov| %>
                        <% if pov.option_value.option_type.name.downcase == 'size' %>
                            <%= pov.option_value.presentation %>
                        <% end %>
                    <% end %>

                    <% item.ad_hoc_option_values.each do |pov| %>
                        <% if pov.option_value.option_type.name.downcase == 'patch' %>
                            <%#= pov.option_value.presentation %>
                            <%= "+ #{pov.option_value.presentation}" unless pov.option_value.presentation.empty? %>
                        <% end %>
                    <% end %>

                  </td>

                  <td>
                    <% if inventory_unit.shipment == @shipment %>
                        <%= t('included_in_this_shipment') %>
                    <% elsif !inventory_unit.shipment_id.nil? %>
                        <%= t('included_in_this_shipment') %>
                        - <%= link_to inventory_unit.shipment.number, edit_admin_order_shipment_url(inventory_unit.order, inventory_unit.shipment) %>
                    <% end %>
                  </td>
                </tr>
            <% end %>
          </table>

        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate(@orders, :previous_label => "&#171; #{t('previous')}", :next_label => "#{t('next')} &#187;") %>


<% content_for :sidebar do %>
    <div class="box">
      <h3><%= t(:search) %></h3>
      <%= form_for [:admin, @search] do |f| %>
          <%- locals = {:f => f} %>
          <%= hook :admin_orders_index_search, locals do %>
              <label><%= t("date_range") %></label><br/>

              <div class="yui-g date-range-filter">
                <div class="yui-u sub-field first">
                  <%= f.spree_date_picker :created_at_greater_than %>
                  <br/>
                  <label class="sub"><%= t("start") %></label>
                </div>
                <div class="yui-u sub-field">
                  <%= f.spree_date_picker :created_at_less_than %>
                  <br/>
                  <label><%= t("stop") %></label>
                </div>
              </div>


              <p><label><%= t 'order_number' %></label><br/>
                <%= f.text_field :number_like, :size=>25 %></p>

              <p>
                <label><%= t 'email' %></label><br/>
                <%= f.text_field :email_like, :size=>25 %>
              </p>


          <% end %>
          <%= hook :admin_orders_index_search_buttons, locals do %>
              <p><%= button t("search") %></p>
          <% end %>
      <% end %>
    </div>
<% end %>

app/views/admin/orders/index.html.erb
<div class='toolbar order-links'>
   <%= hook :admin_order_show_buttons do %>
     <%= button_link_to(t('shipment_report'), "/admin/shipments/print.pdf", :method => :get,  :target => "_blank") %>
  <% end %>
</div>

<%= render :partial => 'admin/shared/order_sub_menu' %>

<h1><%= t("listing_orders") %></h1>


<table class="index" id='listing_orders'>
  <thead>
  <tr>
    <%= hook :admin_orders_index_headers do %>
        <% if @show_only_completed %>
            <th><%= sort_link @search, :completed_at, t("activerecord.attributes.order.completed_at") %></th>
        <% else %>
            <th><%= sort_link @search, :created_at, t("order_date") %></th>
        <% end %>
        <th><%= sort_link @search, :number, t("order_number") %></th>
        <th><%= sort_link @search, :state, t("status") %></th>
        <th><%= sort_link @search, :payment_state, t("payment_state") %></th>
        <th><%= t("purchase_total") %></th>
        <th><%= sort_link @search, :shipment_state, t("shipment_state") %></th>
        <th><%= sort_link @search, :email, t("customer") %></th>
        <th><%= sort_link @search, :total, t("total") %></th>
    <% end %>
    <th>
      <%= hook :admin_orders_index_header_actions %>
    </th>
  </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
      <tr>
        <%- locals = {:order => order} %>
        <%= hook :admin_orders_index_rows, locals do %>
            <td><%= (@show_only_completed ? order.completed_at : order.created_at).to_date %></td>
            <td><%= link_to order.number, admin_order_path(order) %></td>
            <td><%= t("order_state.#{order.state.downcase}") %></td>
            <td><%= link_to t("payment_states.#{order.payment_state}"), admin_order_payments_path(order) if order.payment_state %></td>
            <td><%= "#{order.inventory_units.in_stock.size} in #{order.inventory_units.size}" %></td>
            <td><%= link_to t("shipment_states.#{order.shipment_state}"), admin_order_shipments_path(order) if order.shipment_state %></td>
            <td><%= order.email %></td>
            <td><%= number_to_currency order.total %></td>
        <% end %>
        <td class='actions'>
          <%= hook :admin_orders_index_row_actions, locals do %>
              <%= link_to_edit_url edit_admin_order_path(order), :title => "admin_edit_#{dom_id(order)}" %>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate(@orders, :previous_label => "&#171; #{t('previous')}", :next_label => "#{t('next')} &#187;") %>


<% content_for :sidebar do %>
    <div class="box">
      <h3><%= t(:search) %></h3>
      <%= form_for [:admin, @search] do |f| %>
          <%- locals = {:f => f} %>
          <%= hook :admin_orders_index_search, locals do %>
              <label><%= t("date_range") %></label><br/>

              <div class="yui-g date-range-filter">
                <div class="yui-u sub-field first">
                  <%= f.spree_date_picker :created_at_greater_than %>
                  <br/>
                  <label class="sub"><%= t("start") %></label>
                </div>
                <div class="yui-u sub-field">
                  <%= f.spree_date_picker :created_at_less_than %>
                  <br/>
                  <label><%= t("stop") %></label>
                </div>
              </div>

              <p><label><%= t("status") %></label><br/>
                <%= f.select :state_equals, Order.state_machines[:state].states.collect { |s| [t("order_state.#{s.name}"), s.value] }, {:include_blank => true} %>
              </p>

              <p><label><%= t 'order_number' %></label><br/>
                <%= f.text_field :number_like, :size=>25 %></p>

              <p>
                <label><%= t 'email' %></label><br/>
                <%= f.text_field :email_like, :size=>25 %>
              </p>

              <p>
                <label><%= t 'first_name_begins_with' %></label><br/>
                <%= f.text_field :bill_address_firstname_starts_with, :size=>25 %>
              </p>

              <p>
                <label><%= t 'last_name_begins_with' %></label><br/>
                <%= f.text_field :bill_address_lastname_starts_with, :size=>25 %>
              </p>

              <p>
                <%= f.check_box :completed_at_is_not_null, {:checked => @show_only_completed}, "1", "" %>
                <label>
                  <%= t("show_only_complete_orders") %>
                </label>
              </p>
          <% end %>
          <%= hook :admin_orders_index_search_buttons, locals do %>
              <p><%= button t("search") %></p>
          <% end %>
      <% end %>
    </div>
<% end %>

app/views/admin/orders/show.html.erb
<div class='toolbar order-links'>
  <%= hook :admin_order_show_buttons do %>
    <%= button_link_to t("cancel"), fire_admin_order_url(@order.number, {:e => "cancel"}), :icon => 'delete', :confirm => t('are_you_sure') if @order.can_cancel? %>
    <%= button_link_to t("edit"), edit_admin_order_url(@order.number), :icon => 'edit' %>
  <% end %>
</div>

<%= render :partial => 'admin/shared/order_tabs', :locals => {:current => "Order Details"} %>

<%= hook :admin_order_show_addresses do %>
  <% if @order.ship_address %>
    <div class='adr'>
      <h4><%= t("ship_address") %></h4>
      <%= render :partial => 'admin/shared/address', :locals => {:address => @order.ship_address} %>
    </div>
    <% end %>
  <hr />
<% end %>

<%= hook :admin_order_show_details do %>
  <%= render :partial => 'admin/shared/order_details', :locals => {:order => @order} %>
<% end %>