config/routes.rb
App::Application.routes.draw do



  #match 'admin/order/:id/purchase/new', :to => 'admin/_purchases#new'

  match 'admin/shipments/print', :to => "admin/shipments#print"

  match 'admin/shipments/print_preview', :to => "admin/shipments#print_preview"


  match 'admin/shipments/download', :to => "admin/shipments#download"

  match 'admin/purchases/download', :to => "admin/purchases#download"

  match '/admin/shipments', :to => "admin/shipments#home"

  match '/admin/orders/:order_id/shipments/new', :to => "admin/shipments#add"

  match 'tracking/:id',  :to => "orders#track"

  match '/checkout' => 'checkout#edit', :state => 'delivery', :as => :checkout

  resources :comments
  #resources :tickets



  namespace :admin do
    resources :suppliers
    resources :comments
    resources :tickets
    resources :excels
    resources :refunds
    resources :black_lists

    resources :purchases do
      resources :receive_products
      resources :return_products
    end
  end




end

app/models/ticket.rb
class Ticket < ActiveRecord::Base

  acts_as_commentable


  belongs_to :question_category
  belongs_to :user

  has_attached_file :attachment, :path => ":rails_root/public/assets/tickets/:id/:basename.:extension"

  validates_attachment_size :attachment, :less_than => 2.megabytes
  validates_attachment_content_type :attachment, :content_type => ['image/jpeg', 'image/png', 'image/gif']

  scope :by_customer, lambda {|customer| joins(:user).where("users.email =?", customer)}

  validates_presence_of :title

end

app/controllers/admin/tickets_controller.rb
class Admin::TicketsController < Admin::BaseController
  before_filter :load_object, :only => [:index, :show, :edit, :update]
  before_filter :load_ticket, :only => [:show, :edit, :update]
  #helper :users


  respond_to :html


  def index
    @tickets = Ticket.all
   # @ticket = Ticket.new(:user_id => current_user.id, :question_category_id => QuestionCategory.first.id)
    respond_with(@tickets)
  end



  def create
     @ticket = Ticket.new(params[:ticket])
     if @ticket.save

     else

     end

     redirect_to admin_tickets_url
  end

  #def show
  #  @ticket = Ticket.new(params[:ticket])
  #  respond_with(@ticket)
  #  #@ticket.user.email
  #end



  def update

    if @ticket.update_attributes(params[:ticket])
      flash.notice = t('purchase_update')
      redirect_to edit_admin_ticket_url(@ticket)
    else
      flash[:error] = t('cannot_perform_operation')
      redirect_to edit_admin_ticket_url(@ticket)
    end
  end







  private
    def load_object
      @user ||= current_user
      authorize! params[:action].to_sym, @user
    end

    def load_ticket
       @ticket = Ticket.find(params[:id])
    end

end

app/controllers/tickets_controller.rb
class TicketsController < Spree::BaseController
  before_filter :load_object, :only => [:index, :show, :edit, :update]
  before_filter :load_ticket, :only => [:show, :edit, :update]
  helper :users


  respond_to :html


  def index
    unless current_user.nil?
      @tickets = Ticket.find_all_by_user_id(current_user.id)
      @ticket = Ticket.new(:user_id => current_user.id, :question_category_id => QuestionCategory.first.id)
      respond_with(@tickets)
    else
      redirect_to :login
    end
  end


  def create
    @ticket = Ticket.new(params[:ticket])
    if @ticket.save

    else

    end

    redirect_to tickets_url
  end


  def update

    if @ticket.update_attributes(params[:ticket])
      flash.notice = t('purchase_update')
      redirect_to edit_ticket_url(@ticket)
    else
      flash[:error] = t('cannot_perform_operation')
      redirect_to edit_ticket_url(@ticket)
    end
  end


  private
  def load_object
    @user ||= current_user
    #authorize! params[:action].to_sym, @user
  end

  def load_ticket
    @ticket = Ticket.find(params[:id])
  end

end

app/helpers/ticket_helper.rb
module TicketHelper
end

app/views/admin/tickets/_form.html.erb
<%- locals = {:f => f} -%>
<%= f.hidden_field :user_id %>
<p class="admin_line_items_show_details">
  <%= f.label :title, t("title") %><br/>
  <%= f.text_field :title, :class => 'fullwidth title' %>
</p>
<p class="admin_line_items_show_details">
  <%= f.label :question_categories, t("question_categorie") %> <span class="required">*</span><br/>
  <%= f.collection_select(:question_category_id, QuestionCategory.all, :id, :name) %>
</p>

<p class="admin_line_items_show_details">
  <%= f.label :comment, t("comment") %><br/>
  <%= f.text_area :comment, {:style => 'height:150px;', :class => 'fullwidth'} %>
</p>

app/views/admin/tickets/index.html.erb
<h1><%= "#{t("actions.listing")} #{t("tickets")}" %></h1>

<table class="index">
  <tr>
    <th><%= t("ticket") %></th>
    <th><%= "#{t('spree.date')}/#{t('spree.time')}" %></th>
    <th><%= t("title") %></th>

    <th><%= t("department") %></th>
    <th><%= t("replies") %></th>
    <th><%= t("status") %></th>
    <th></th>
  </tr>
  <% @tickets.each do |ticket| %>
      <tr id="<%= dom_id ticket %>">
        <%- locals = {:ticket => ticket} %>
        <td><%= ticket.id %></td>
        <td><%= ticket.created_at.to_s(:date_time24) if ticket.created_at %></td>
        <td><%= link_to ticket.title, admin_ticket_path(ticket) %></td>

        <td><%= ticket.question_category.name %></td>
        <td><%= ticket.comments.count %></td>

        <td><%= ticket.status %></td>
      </tr>
  <% end %>
</table>

app/views/admin/tickets/new.html.erb
<%= render 'shared/error_messages', :target => @ticket %>
<h1><%= t("new_ticket") %></h1>


<%= form_for(@ticket, :url => admin_ticket_path(@ticket)) do |f| %>
    <%= render :partial => "form", :locals => {:f => f} %>


<%= hook :admin_purchase_new_form_buttons do %>
    <p class="form-buttons">
      <%= button t('create') %>
    </p>
  <% end %>

<% end %>

app/views/admin/tickets/show.html.erb
<h2>Ticket : <%= @ticket.title %></h2>

<table class="index">
  <tbody>
  <tr>
    <th style="width:140px;">Date/Time</th>

    <th>Comment</th>
  </tr>
  <tr id="comment_1">
    <td><%= @ticket.created_at.to_formatted_s(:long) %></td>

    <td>
      <div class="order-comment-header" id="order-comment-header-0">
        <strong><%= @ticket.user.email %> said :</strong>
      </div>
      <div class="order-comment-body" id="order-comment-body-0">
        <%= @ticket.comment.html_safe %>
      </div>
      <div class="order-comment-body" id="order-comment-body-0">
        <% unless @ticket.attachment_file_name.blank?  %>
            <%= image_tag "http://#{Store.find(@ticket.store_id).domains}/assets/tickets/#{@ticket.id}/#{@ticket.attachment_file_name}" %>
        <% end %>
      </div>
    </td>
  </tr>
  </tbody>
</table>

<%= render "admin/shared/comments", :commentable => @ticket %>