config/routes.rb
App::Application.routes.draw do



  #match 'admin/order/:id/purchase/new', :to => 'admin/_purchases#new'

  match 'admin/shipments/print', :to => "admin/shipments#print"

  match 'admin/shipments/print_preview', :to => "admin/shipments#print_preview"


  match 'admin/shipments/download', :to => "admin/shipments#download"

  match 'admin/purchases/download', :to => "admin/purchases#download"

  match '/admin/shipments', :to => "admin/shipments#home"

  match '/admin/orders/:order_id/shipments/new', :to => "admin/shipments#add"

  match 'tracking/:id',  :to => "orders#track"

  match '/checkout' => 'checkout#edit', :state => 'delivery', :as => :checkout

  resources :comments
  #resources :tickets



  namespace :admin do
    resources :suppliers
    resources :comments
    resources :tickets
    resources :excels
    resources :refunds
    resources :black_lists

    resources :purchases do
      resources :receive_products
      resources :return_products
    end
  end




end

app/views/shared/store1/_checkout_edit.html.erb
<div class="grid_16" style="margin-left: 0px;margin-right:0px;width: 960px;">
  <div id="body_content">
    <div class="top-box-960"></div>
    <div class="title-960">
      <h1><%= t("checkout")%></h1>
    </div>
    <div class="content-960 clearfix">
      <div id="checkout" class="clearfix">
        <%= checkout_progress %>
      </div>
      <%= render "shared/error_messages", :target => @order %>

      <%= hook :checkout_summary_box do %>
          <div id="checkout-summary" class="clearfix">
            <%= render 'summary', :order => @order %>
            <div class="clear"></div>
          </div>
      <% end %>

      <%= form_for @order, :url => update_checkout_path(@order.state), :html => { :id => "checkout_form_#{@order.state}" } do |form| %>
          <%= render @order.state, :form => form %>
          <input id="post-final" type="submit" style="display:none"/>
      <% end %>

      <div class="clear"></div>
    </div>
    <div class="footer-960"></div>
  </div>
</div>

app/views/shared/store1/_faq_index.html.erb
<div class="grid_16" style="margin-left: 0px;margin-right:0px;width: 960px;">
  <div id="body_content">
    <div class="top-box-960"></div>
    <div class="title-960">
      <h1><%= t('frequently_asked_questions') %></h1>
    </div>
    <div class="content-960">
      <div id="faqs">
        <% @categories.each do |category| %>
            <div id="<%= dom_id category -%>" class="category">
              <h2><%= h category.name %></h2>
              <ul class="answers">
                <% category.questions.each do |question| %>
                    <li>
                      <a class="question" id="<%= dom_id question -%>" href="#<%= "answer_#{question.id}" %>">
                        <%= h question.question -%>
                      </a>
                      <div class="answer" id="<%= "answer_#{question.id}"-%>">
                        <%= question.answer %>
                      </div>
                    </li>
                <% end %>
              </ul>
            </div>
        <% end %>
      </div>
    </div>
    <div class="footer-960"></div>
  </div>
</div>

app/views/shared/store1/_head.html.erb
<title><%= site_title %></title>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<%== meta_data_tags %>
<%= stylesheet_link_tag 'footballshirt/reset.css', 'footballshirt/text.css', 'footballshirt/960.css','footballshirt/screen.css' %>
<%= csrf_meta_tag %>
<%= javascript_include_tag 'jquery-1.4.2.min', 'jquery.validate.min.js', 'rails', 'application', :cache => 'jquery-core' %>
<% unless I18n.locale.to_s[0..1] == 'en' %>
  <%= javascript_include_tag ['localization/messages_', I18n.locale.to_s[0..1], '.js'].join %>
<% end %>
<%= yield :head %>

app/views/shared/store1/_list_products.html.erb
<%
  paginated_products = @searcher.products if params.key?(:keywords)
  paginated_products ||= products
%>


            <div class="content content-770 clearfix">

                <% if products.empty? %>
                    <%= t(:no_products_found) %>
                <% elsif params.key?(:keywords) %>
                    <h3><%= t(:search_results, :keywords => h(params[:keywords])) %></h3>
                <% end %>


                <% if products.any? %>
                <ul class="product-listing">
                  <% products.each do |product| %>
                    <% if Spree::Config[:show_zero_stock_products] || product.has_stock? %>
                      <li id="product_<%= product.id %>">
                        <div class="grid_4 grid-product-list">
                            <div class="product-entry clearfix">
                        <%= hook :products_list_item, {:product => product} do %>
                          <%= link_to product_image(product), product %>
                          <%= link_to raw("<span class='item-title'>" + product.name + "</span>"+ " <span class='price'>#{product_price(product)}</span>" + "<span class='add-to-cart'></span>"), product %>
                        <% end %>
                            </div>
                        </div>
                      </li>
                    <% end %>
                  <% end %>
                </ul>
                <% end %>

                <div class="clear"></div>
            </div>



<% if paginated_products.respond_to?(:total_pages)
      params.delete(:search)
      params.delete(:taxon)

%>
<%= will_paginate(paginated_products,
                    :previous_label => "&#171; #{t('previous')}",
                    :next_label => "#{t('next')} &#187;") %>
<% end %>

app/views/shared/store1/_list_products_all_taxon.html.erb
<%
  paginated_products = @searcher.products if params.key?(:keywords)
  paginated_products ||= products
%>


            <div class="content content-770 clearfix">
                <h2 class="list-taxon" style="color: #333;"><%= link_to taxon.name, seo_url(taxon), :class => 'breadcrumbs' %></h2>

                <% if products.empty? %>
                    <%= t(:no_products_found) %>
                <% elsif params.key?(:keywords) %>
                    <h3><%= t(:search_results, :keywords => h(params[:keywords])) %></h3>
                <% end %>


                <% if products.any? %>
                <ul class="product-listing">
                  <% products.each do |product| %>
                    <% if Spree::Config[:show_zero_stock_products] || product.has_stock? %>
                      <li id="product_<%= product.id %>">
                        <div class="grid_4 grid-product-list">
                            <div class="product-entry clearfix">
                        <%= hook :products_list_item, {:product => product} do %>
                          <%= link_to product_image(product), product %>
                          <%= link_to raw("<span class='item-title'>" + product.name + "</span>"+ " <span class='price'>#{product_price(product)}</span>" + "<span class='add-to-cart'></span>"), product %>
                        <% end %>
                            </div>
                        </div>
                      </li>
                    <% end %>
                  <% end %>
                </ul>
                <% end %>

                <div class="clear"></div>
            </div>



<% if paginated_products.respond_to?(:total_pages)
      params.delete(:search)
      params.delete(:taxon)

%>
<%= will_paginate(paginated_products,
                    :previous_label => "&#171; #{t('previous')}",
                    :next_label => "#{t('next')} &#187;") %>
<% end %>

app/views/shared/store1/_no_products_search.html.erb
<div class="grid_13" style="margin-right: 0;width:770px;">
  <div id="body_content">
    <div class="top-box-770"></div>
    <div class="title">
      <%= t(:no_products_found) %>
    </div>
    <div class="footer-770"></div>
  </div>
</div>

app/views/shared/store1/_order_description.html.erb
<div class="content content-770">
    <h3>Items Descriptions</h3>
    <p>Brand new, never worn and come with tags. <br/> 100% High quality material.</p>

    <p class="topic_item">Size Available</p>
    <p>  - Size : M   (Chest Length 40-42 Inches,Length 27-29 Inches) <br/>
         - Size : XL  (Chest Length 45-47 Inches,Length 30-32 Inches)</p>

    <p class="topic_item">Special Promotions.</p>
    <p> - Customers can customize all name and number for FREE.<br/>
        - If customers purchase more than 7 shirts per order, we will ship order by Express Air Mail.
        </p>

    <p class="topic_item">Shipping and Return Policy</p>
    <p>
      - Shipping will take around 2 - 4 weeks depended on your location.<br/>
       - Shipping cost is 8.00 GBP for first item and 6.00 GBP for each additional items in the same package.<br/>
       - Please wait around 4 weeks before open a claim or contact us first. We will solve all problems.<br/>
       - Shipping is by DHL air mail or Express air mail.

    </p>

    <p>Your satisfaction is 100% guarantee. If you don't happy with my items in any reason, I will give you full refund or send you the new one.
</p>

</div>

app/views/shared/store1/_products.html.erb
<%
  paginated_products = @searcher.products if params.key?(:keywords)
  paginated_products ||= products
%>
<div class="grid_13" style="margin-right: 0;width:770px;">
    <div id="product-list">
        <h2 class="left-topic">Latest Products</h2>
        <div class="top-box-770"></div>
            <div class="content content-770 clearfix">

                <% if products.empty? %>
                    <%= t(:no_products_found) %>
                <% elsif params.key?(:keywords) %>
                    <h3><%= t(:search_results, :keywords => h(params[:keywords])) %></h3>
                <% end %>


                <% if products.any? %>
                <ul class="product-listing">
                  <% products.each do |product| %>
                    <% if Spree::Config[:show_zero_stock_products] || product.has_stock? %>
                      <li id="product_<%= product.id %>">
                        <div class="grid_4 grid-product-list">
                            <div class="product-entry clearfix">
                        <%= hook :products_list_item, {:product => product} do %>
                          <%= link_to product_image(product), product %>
                          <%= link_to raw("<span class='item-title'>" + product.name + "</span>"+ " <span class='price'>#{product_price(product)}</span>" + "<span class='add-to-cart'></span>"), product %>
                        <% end %>
                            </div>
                        </div>
                      </li>
                    <% end %>
                  <% end %>
                </ul>
                <% end %>

                <div class="clear"></div>
            </div>
        <div class="footer-770"></div>
        <!-- last product -->
    </div>
    <!-- product-list -->
</div>

<% if paginated_products.respond_to?(:total_pages)
      params.delete(:search)
      params.delete(:taxon)

%>
<%= will_paginate(paginated_products,
                    :previous_label => "&#171; #{t('previous')}",
                    :next_label => "#{t('next')} &#187;") %>
<% end %>

app/views/shared/store1/_search.html.erb
<% 
	#@taxons = @taxon && @taxon.parent ? @taxon.parent.children : Taxon.roots  
%> 
<%= form_tag products_url, :method => :get ,:class =>"search-box" do %>
  <%
   # select_tag :taxon, 
   #     options_for_select([[t(:all_departments), '']] + 
   #                           @taxons.map {|t| [t.name, t.id]}, 
   #                         @taxon ? @taxon.id : params[:taxon]) 
   %>
  <p><%= text_field_tag :keywords, params[:keywords] %></p>
  <%= submit_tag t(:search), :name => nil %>
<% end %>

app/views/shared/store1/_show.html.erb
<% @body_id = 'product-details' %>

<% content_for :sidebar do %>
    <%= render "shared/taxonomies" %>
<% end %>
<%= render "shared/footballshirt/sidebar_left"  %>

<div class="grid_13" style="margin-right: 0;width:770px;">
  <div id="body_content">
    <div class="top-box-770"></div>
    <div class="title">
      <h1><%= accurate_title %></h1>
    </div>
    <div class="content content-770" style="padding-bottom: 0;">
      <div id="product-images">
        <%= hook :product_images do %>
            <div id="main-image">
              <%= render 'image' %>
            </div>
            <div id="thumbnails" class="clearfix">
              <%= render 'thumbnails', :product => @product %>
              <div class="clear"></div>
            </div>
        <% end %>
      </div>
      <div id="product-description">
        <%= hook :product_description do %>
            <%= product_description(@product) rescue t("product_has_no_description") %>
        <% end %>
        <%= hook :product_properties do %>
            <%#= render 'properties' %>
        <% end %>
      </div>
      <div class="customize">
        <%= hook :cart_form do %>
            <div id="cart-form">
              <%= render 'cart_form' %>
            </div>
        <% end %>

      </div>
      <%#= render 'taxons' %>
    </div>
    <%= render 'shared/footballshirt/order_description' %>
    <div class="footer-770"></div>
  </div>
</div>

app/views/shared/store1/_sidebar_left.html.erb
<div class="grid_3" style="width:170px; margin-left: 0px;">
  <%= render "shared/footballshirt/sidebar/categories_sidebar" %>
  <div class="clear"></div>
  <%= render "shared/footballshirt/sidebar/cart_sidebar" %>
  <%= render "shared/top_seller" %>

</div>
<!-- grid_3 sidebar-->

app/views/shared/store1/_sidebar_right.html.erb
        <div class="grid_3" style="width:170px; margin-right: 0px;">
            <%= render "shared/footballshirt/sidebar/cart_sidebar" %>
            <%= render "shared/footballshirt/sidebar/payment_sidebar" %>
            <%= render "shared/footballshirt/sidebar/banner_sidebar" %>
        </div>

app/views/shared/store1/_user_form.html.erb
<p>
  <%= f.label :email, t("email") %><br />
  <%= f.text_field :email, :class => 'title-input'  %>
</p>
<div id="password-credentials">
  <p>
    <%= f.label :password, t("password") %><br />
    <%= f.password_field :password, :class => 'title-input'  %>
  </p>

  <p>
    <%= f.label :password_confirmation, t(:confirm_password) %><br />
    <%= f.password_field :password_confirmation, :class => 'title-input' %>
  </p>
</div>

<%= hook :signup_below_password_fields %>

app/views/shared/store1/_welcome_msg.html.erb
            <div id="body_content">
                <div id="banner-slider">
                    <%= image_tag('footballshirt/home/football_story_banner.jpg') %>
                </div>
                <div class="top-box"></div>
                <div class="title">
                    <% if flash.notice %>
                        <div class="flash notice"><%= flash.notice %></div>
                    <% end %>
                    <% if flash[:error] %>
                        <div class="flash errors"><%= flash[:error] %></div>
                    <% end %>
                    <p class="topic_item">Welcome to Footballshirtmarket.com</p>
                    <p>Find the largest collection of football shirt online at your finger tips. <br/>
                         The online football shirt store has all of your favourite club and<br/>
                         national teams football shirts and offering in very reasonable prices. Let's find out more.</p>
                    <br/>
                </div>
                <div class="content">
                    <p class="topic_item">Safe and Secure</p>
                    <p>Safe and secure when you buy from Footballshirtmarket.com</p>
                    <p>- You not need to add any credit card in this website.We will not ask you  any credit card information from you.</p>

                </div>
                <div class="footer"></div>
                <!-- welcom msg -->
            </div>
            <!-- body_content -->