config/routes.rb
App::Application.routes.draw do



  #match 'admin/order/:id/purchase/new', :to => 'admin/_purchases#new'

  match 'admin/shipments/print', :to => "admin/shipments#print"

  match 'admin/shipments/print_preview', :to => "admin/shipments#print_preview"


  match 'admin/shipments/download', :to => "admin/shipments#download"

  match 'admin/purchases/download', :to => "admin/purchases#download"

  match '/admin/shipments', :to => "admin/shipments#home"

  match '/admin/orders/:order_id/shipments/new', :to => "admin/shipments#add"

  match 'tracking/:id',  :to => "orders#track"

  match '/checkout' => 'checkout#edit', :state => 'delivery', :as => :checkout

  resources :comments
  #resources :tickets



  namespace :admin do
    resources :suppliers
    resources :comments
    resources :tickets
    resources :excels
    resources :refunds
    resources :black_lists

    resources :purchases do
      resources :receive_products
      resources :return_products
    end
  end




end

app/models/black_list.rb
class BlackList < ActiveRecord::Base
end

app/controllers/admin/black_lists_controller.rb
class Admin::BlackListsController < Admin::ResourceController

end

app/helpers/black_lists_helper.rb
module BlackListsHelper
end

app/views/admin/black_lists/_form.html.erb
<table>
  <tr>
    <td><label>IP</label></td>
    <td><%= text_field :black_list, :ip, {"style" => "width:150px"} %></td>
  </tr>
  <tr>
    <td><label>Reason</label></td>
    <td><%= text_field :black_list, :reason, {"style" => "width:300px"} %></td>
  </tr>

</table>

app/views/admin/black_lists/edit.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<h1>Edit Black List</h1>
<%= render "shared/error_messages", :target => @black_list %>
<%= form_for(@black_list, :url => object_url, :html => { :method => :put }) do |f| %>
    <%= render :partial => "form", :locals => { :f => f } %>
    <p class="form-buttons">
      <%= button t('update') %>
      <%= t("or") %> <%= link_to t("actions.cancel"), admin_black_lists_url %>
    </p>
<% end %>

app/views/admin/black_lists/index.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<div class='toolbar'>
  <ul class='actions'>
    <li>
      <%= button_link_to "New Black List", new_object_url, :icon => 'add'  %>
    </li>
  </ul>
  <br class='clear' />
</div>

<h1>Black Lists</h1>

<table class="index">
  <thead>
  <th>IP</th>
  <th>Reason</th>

  <th><%= t("action") %></th>
  </thead>
  <tbody>
  <% @black_lists.each do |black_list|%>
      <tr id="<%= dom_id black_list %>">
        <td width="120px"><%= black_list.ip %></td>
        <td width="200px"><%= black_list.reason %></td>


        <td width="140px">
          <%= link_to_edit black_list %> &nbsp;
          <%= link_to_delete black_list %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/black_lists/new.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<h1>New Black List</h1>
<%= render "shared/error_messages", :target => @black_list %>

<%= form_for(:black_list, :url => collection_url) do |f| %>
    <%= render :partial => "form", :locals => { :f => f } %>
    <p class="form-buttons">
      <%= button t('continue') %>
      <%= t("or") %> <%= link_to t("actions.cancel"), admin_black_lists_url %>
    </p>
<% end %>